name: Mongo Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Start MongoDB v4.2
        uses: superchargejs/mongodb-github-action@1.1.0
        with:
          mongodb-version: 4.2

      - run: npm install

      - run: npm test
