name: Mongo Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Create mongo Docker container
        id: build_mongo_docker
        uses: StefanoDeVuono/mongodb-github-action@7cdb383b82b268afea3c1064e3b47743e3004c0f

      - run: npm install

      - run: npm test
